### PR TITLE
Fixed obvious typo (PDFALSE should be pdFALSE in src/os/OSSelectWakeup.cxx).

### PR DESCRIPTION
**Pull request by RobertPHeller**
There is a minor typo in src/os/OSSelectWakeup.cxx (aka OSSelectWakeup.cpp) that breaks building using the OpenMRNLite library (Arduino IDE for ESP32).  This just fixes that typo.  The constant is camel cased, not all uppercase, as defined in os.hxx.

### CODE REVIEW

**Comment by atanisoft** [comment]
@RobertPHeller Can you send a new PR without the extra commits? I agree though that this should get fixed.

**Comment by atanisoft** [comment]
also unsure how this got missed as my copy is set as ```pdFALSE``` ...

**Comment by RobertPHeller** [comment]
I am not sure how to create a new PR without the extra commits.

**Comment by atanisoft** [comment]
Please see PR #326. If you navigate to the file on this repo and click edit it will allow you create a PR directly from the edit.

**Pull request closed without merging**
